{"uuid":"0dcc2eb0-7328-4a04-862c-4f8ac3f3b91e","historyId":"78914db0bc84c89d2c2a7f07796a20fa","fullName":"TestClass.EndToEndTest.E2ETest.testLoginWithInvalidCredentials","labels":[{"name":"package","value":"TestClass.EndToEndTest.E2ETest"},{"name":"testClass","value":"TestClass.EndToEndTest.E2ETest"},{"name":"testMethod","value":"testLoginWithInvalidCredentials"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"testing.xml"},{"name":"subSuite","value":"TestClass.EndToEndTest.E2ETest"},{"name":"host","value":"Mohamed-Nasser.local"},{"name":"thread","value":"3788@Mohamed-Nasser.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Mohamed Nasser"},{"name":"severity","value":"critical"}],"links":[{"name":"https://www.automationexercise.com/login","type":"custom"}],"name":"testLoginWithInvalidCredentials","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Method TestClass.EndToEndTest.E2ETest.testLoginWithInvalidCredentials() on instance TestClass.EndToEndTest.E2ETest@9635fa depends on not successfully finished methods \n[TestClass.EndToEndTest.E2ETest.testLoginWithValidCredentials() on instance TestClass.EndToEndTest.E2ETest@9635fa]","trace":"java.lang.Throwable: Method TestClass.EndToEndTest.E2ETest.testLoginWithInvalidCredentials() on instance TestClass.EndToEndTest.E2ETest@9635fa depends on not successfully finished methods \n[TestClass.EndToEndTest.E2ETest.testLoginWithValidCredentials() on instance TestClass.EndToEndTest.E2ETest@9635fa]\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\n\tat org.testng.TestRunner.run(TestRunner.java:614)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Verify system shows an error message when logging in with invalid credentials...","steps":[],"attachments":[],"parameters":[],"start":1737143061898,"stop":1737143061898}